services:
  client:
    build: ./packages/client
    env_file:
      - ./packages/client/.env
    ports:
      - "80:80"
  server:
    build: ./packages/server
    env_file:
      - .env
    ports:
      - "3000:3001"